const MENU_ITEMS = [
    { key: 'navigation', label: 'Navigation', isTitle: true },
    {
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: 'uil-dashboard',
        url: '/bmg/dashboard',
    },
    {
        key: 'leads',
        label: 'Auction Leads',
        isTitle: false,
        icon: 'uil-chart',
        url: '/bmg/leads',
    },
    {
        key: 'live-bids',
        label: 'Live Bids',
        isTitle: false,
        icon: 'uil-monitor-heart-rate',
        url: '/bmg/live-bids',
    },
    {
        key: 'categories',
        label: 'Categories',
        isTitle: false,
        icon: 'uil-cell',
        url: '/bmg/categories',
    },
    {
        key: 'items',
        label: 'Items',
        isTitle: false,
        icon: 'uil-box',
        url: '/bmg/items',
    },
    {
        key: 'sold-items',
        label: 'Sold Items',
        isTitle: false,
        icon: ' uil-image-broken',
        url: '/bmg/sold-items',
    },
    {
        key: 'users',
        label: 'Users',
        isTitle: false,
        icon: ' uil-users-alt',
        url: '/bmg/users',
    },
    {
        key: 'orders',
        label: 'Orders',
        isTitle: false,
        icon: 'uil-list-ui-alt',
        url: '/bmg/orders',
    },
    {
        key: 'transactions',
        label: 'Transactions',
        isTitle: false,
        icon: ' uil-usd-circle',
        url: '/bmg/transactions',
    },
    {
        key: 'platform-charges',
        label: 'Platform Charges',
        isTitle: false,
        icon: 'uil-bill',
        url: '/bmg/platform-charges',
    },
    {
        key: 'faq',
        label: 'Faq',
        isTitle: false,
        icon: ' uil-comment-exclamation',
        url: '/bmg/faq',
    },
    {
        key: 'notification',
        label: 'Notification',
        isTitle: false,
        icon: 'uil-comment-alt-notes',
        url: '/bmg/notification',
    },
    {
        key: 'enquiry',
        label: 'Enquiry',
        isTitle: false,
        icon: 'uil-comments-alt',
        url: '/bmg/enquiry',
    },

];

export default MENU_ITEMS;
